import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import styles from './index.module.scss';
import fs from 'fs';
import {getFirstPageNameForEachNavItem} from '../lib/dataFetch';
import {kebabCase} from '../lib/utils';
import Header from '../components/Header';
import {barlow, barlowCondensed, bellefair} from '../lib/fonts';

export default function Home(
    {destination, crew, technology}: {
      destination: string, crew: string, technology: string
    }
  ) {

  return (
    <div className={styles.canvas}>
      <div className={styles.background}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className={styles.yPadding}>
          <div className={styles.nav}>
              <Header/>
          </div>
          <div className={styles.xPadding}>
            <div className={styles.textAndBtn}>
              <div className={styles.text}>
                <h5 className={`${styles.heading5Ext} ${barlowCondensed.className}`}>
                  So, you want to travel to
                </h5>
                <h1 className={`${styles.heading1Ext} ${bellefair.className}`}>
                  Space
                </h1>
                <p className={styles.bodyTextExt + ' ' + barlow.className}>
                Let’s face it; if you want to go to space, you might as well genuinely go to 
            outer space and not hover kind of on the edge of it. Well sit back, and relax 
            because we’ll give you a truly out of this world experience!
                </p>
              </div>
              <div className={styles.exploreBtn}>
                <div className={styles.exploreTxt + ' ' + bellefair.className}>
                  Explore
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export function getStaticProps() {
  return {
    props: getFirstPageNameForEachNavItem()
  };
}
