import Head from 'next/head';
// import Image from 'next/image';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import fs from 'fs';
import {getFirstPageNameForEachNavItem} from '../resources/dataFetch';
import {kebabCase} from '../lib/utils';
import Nav from '../components/Nav';

export default function Home(
    {destination, crew, technology}: {
      destination: string, crew: string, technology: string
    }
  ) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav/>
      <h1 className={styles.h1}>
        <small>So, you want to travel to</small>
        <br/>
        Space
      </h1>
      <p>
      Let’s face it; if you want to go to space, you might as well genuinely go to 
  outer space and not hover kind of on the edge of it. Well sit back, and relax 
  because we’ll give you a truly out of this world experience!
      </p>


  Explore


    </div>
  )
}

export function getStaticProps() {
  return {
    props: getFirstPageNameForEachNavItem()
  };
}
